# Generated by Django 3.2.13 on 2022-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pick',
            field=models.CharField(choices=[('issue_a', 'A'), ('issue_b', 'B')], default='issue_a', max_length=15),
        ),
    ]
